
### Get all categories
GET http://localhost:3000/api/categories
### Get all subcategories
GET http://localhost:3000/api/sub-categories


### Post all categories and subcategories
POST http://localhost:3000/api/bulk-categories
Content-Type: application/json

{
    "categories": [
        {
            "name": "kellot",
            "subcategories": [
                {
                    "name": "rannekellot"
                }
            ]
        },
        {
            "name": "puhelimet",
            "subcategories": [
                {
                    "name": "alypuhelimet"
                }
            ]
        },
        {
            "name": "tietokoneet",
            "subcategories": [
                {
                    "name": "kannettavat"
                },
                {
                    "name": "poytakoneet"
                },
                {
                    "name": "tabletit"
                }
            ]
        },
        {
            "name": "koti",
            "subcategories": [
                {
                    "name": "jaakaapit"
                },
                {
                    "name": "siivous"
                }
            ]
        },
        {
            "name": "kamerat",
            "subcategories": [
                {
                    "name": "jarjestelma-kamerat"
                },
                {
                    "name": "digitalCameras"
                }
            ]
        },
        {
            "name": "audio",
            "subcategories": [
                {
                    "name": "kuulokkeet"
                }
            ]
        }
    ]
}

### Post new category
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "id": "e5811ce3-a7c8-4bdc-83e0-99b6965815d1",
    "name": "musiikki"
}

### Post new category
POST http://localhost:3000/api/sub-categories
Content-Type: application/json

{
        "id": "53e0c057-c8d3-4a5a-847d-1f907f4c2907",
        "name": "kosketinsoittimet",
        "categoryId": "e5811ce3-a7c8-4bdc-83e0-99b6965815d1"
}

### Post new category
POST http://localhost:3000/api/sub-categories
Content-Type: application/json

{
    "id": "f4a556e8-2307-460a-885c-5e78e1c3e022 ",
    "name": "peilit",
    "categoryId": "feba1df5-4f00-489f-8a6f-db4f381e2e7b"
}


