### Get all products
GET http://localhost:3000/api/products/

### GET product by id
GET http://localhost:3000/api/products/1

### POST product### POST product
POST http://localhost:3000/api/products/ HTTP/1.1
Content-Type: application/json
{
    "id": 3,
    "imageId": "cd879f3e-bbf0-4f49-befb-ccb2b6c7a990_jitspk",
    "name": "AcmeWatch 3",
    "price": 4990,
    "description": "Acme Watch 3, tilanteeseen kuin tilanteeseen",
    "quantity": 30,
    "categoryId": 1,
    "subcategoryId": 1
}

###

POST http://localhost:3000/api/products
Content-Type: application/json

{
  "id": "4",
  "imageId": "cd879f3e-bbf0-4f49-befb-ccb2b6c7a990_jitspk",
  "name": "AcmeWatch 4",
  "price": 399,
  "description": "Kaunis kello joka sopii kaikille",
  "quantity": 30,
  "categoryId": 1,
  "subcategoryId": 1
}

###

POST http://localhost:3000/api/products
Content-Type: application/json

{
  "id": "4",
  "imageId": "0e2ddb72-97c6-4b9a-9640-f1e91f5fe4d3_l2fhun",
  "name": "AcmePhone 10",
  "price": 599,
  "description": "Vanhempi AcmePhone, 7G, Huikea äänentoisto sekä USB-C yhteensopiva",
  "quantity": 15,
  "categoryId": 3,
  "subcategoryId": 3
}

###

POST http://localhost:3000/api/products
Content-Type: application/json

{
  "id": "6",
  "imageId": "9a73596f-5fb9-4160-87aa-6a35a1721975_a1rblq",
  "name": "Acme LapDragon 3",
  "price": 1290,
  "description": "The best laptop ever",
  "quantity": 15,
  "categoryId": 4,
  "subcategoryId": 4
}

###

POST http://localhost:3000/api/products
Content-Type: application/json

{
  "id": "7",
  "imageId": "d2de67ec-d276-4a1b-9146-c9fd4c235bb7_yzkris",
  "name": "Acme Fr1",
  "price": 659,
  "description": "Moderni jääkaappi kaikiin tarpeisiin",
  "quantity": 10,
  "categoryId": 5,
  "subcategoryId": 7
}

###

POST http://localhost:3000/api/products
Content-Type: application/json

{
  "id": "8",
  "imageId": "54140d93-3cb4-4fd2-bdd1-46116346771a_qceb0i",
  "name": "AcmeClean 700",
  "price": 149,
  "description": "Moderni siivousrobotti, erittäin hiljainen",
  "quantity": 20,
  "categoryId": 5,
  "subcategoryId": 8
}

###

POST http://localhost:3000/api/products
Content-Type: application/json

{
  "id": "9",
  "imageId": "dfe7150f-ac42-4a81-a620-d545b675ddf4",
  "name": "Acme C432",
  "price": 998,
  "description": "The best camera ever",
  "quantity": 15,
  "categoryId": 6,
  "subcategoryId": 9
}

###

POST http://localhost:3000/api/products
Content-Type: application/json

{
  "id": "10",
  "imageId": "c608f458-7f34-49e0-a06d-d6e453341341",
  "name": "AcmePods 4",
  "price": 199,
  "description": "Bluetooth kuulokkeet langattomalla latauksella, laadukas ääni",
  "quantity": 80,
  "categoryId": 7,
  "subcategoryId": 1
}